version: "3"

services:
    npm:
        image: node:14.0.0
        user: node
        working_dir: /home/node
        entrypoint: npm
        command: --help
        volumes:
            - .:/home/node

    npx:
        image: node:14.0.0
        user: node
        working_dir: /home/node
        entrypoint: npx
        command: --help
        ports:
            - 8000:8000
        volumes:
            - .:/home/node
